import React, { useMemo, useState } from 'react';
import { PhoneCall, Plus, ScrollText, Edit, Trash2 } from 'lucide-react';
import { CRM_QUARTER_MONTH_BLOCKS, type CrmSalesPeriod } from './crmActivitiesUtils';
import { crmLeadAttributedToUser, resolveCrmCallCreatorName } from './userProfileMetrics';
import {
    formatCallDueDate,
    isActivityCompleted,
    isCallDueToday,
    leadMatchesDueDatePeriod,
    toLocalYmd,
    accountHasCallHistory,
} from './crmActivitiesUtils';
import { getTagColor } from './tagColorSettings';
import LogCallModal, { type LogCallFormData } from './LogCallModal';
import CallDetailsModal from './CallDetailsModal';
import CrmCallReportView from './CrmCallReportView';

export type CrmActivitiesViewProps = {
    theme: any;
    salesCalls: any[];
    crmSalesPeriod: CrmSalesPeriod;
    createdByUserFilterId: string;
    crmFilterUsers?: { id: string; name: string }[];
    activePropertyId?: string;
    readOnly?: boolean;
    canEditSalesCalls?: boolean;
    canDeleteSalesCalls?: boolean;
    onOpenLeadProfile: (lead: any) => void;
    onLogCallSave: (lead: any, data: LogCallFormData) => void;
    onToggleActivityCompleted: (lead: any, completed: boolean) => void;
    onEditCall?: (lead: any) => void;
    onDeleteCall?: (lead: any) => void;
    onAddSalesCall?: () => void;
};

export default function CrmActivitiesView({
    theme,
    salesCalls,
    crmSalesPeriod,
    createdByUserFilterId,
    crmFilterUsers,
    activePropertyId,
    readOnly = false,
    canEditSalesCalls = false,
    canDeleteSalesCalls = false,
    onOpenLeadProfile,
    onLogCallSave,
    onToggleActivityCompleted,
    onEditCall,
    onDeleteCall,
    onAddSalesCall,
}: CrmActivitiesViewProps) {
    const colors = theme.colors;
    const [todayOnly, setTodayOnly] = useState(true);
    const [listTab, setListTab] = useState<'active' | 'completed' | 'report'>('active');
    const [logCallLead, setLogCallLead] = useState<any | null>(null);
    const [detailsLead, setDetailsLead] = useState<any | null>(null);
    const [followUpHint, setFollowUpHint] = useState<string | null>(null);

    const flatAll = useMemo(() => salesCalls || [], [salesCalls]);

    const propertyFiltered = useMemo(() => {
        const pid = String(activePropertyId || '').trim();
        if (!pid) return flatAll;
        return flatAll.filter((l: any) => {
            const p = String(l?.propertyId || '').trim();
            return !p || p === pid || p === 'P-GLOBAL';
        });
    }, [flatAll, activePropertyId]);

    const userFiltered = useMemo(() => {
        const fid = String(createdByUserFilterId || '').trim();
        if (!fid) return propertyFiltered;
        const userRow = (crmFilterUsers || []).find((u) => String(u.id) === fid);
        if (!userRow) return propertyFiltered;
        return propertyFiltered.filter((l: any) => crmLeadAttributedToUser(l, { id: userRow.id, name: userRow.name }));
    }, [propertyFiltered, createdByUserFilterId, crmFilterUsers]);

    const periodFiltered = useMemo(() => {
        if (todayOnly) {
            const today = toLocalYmd();
            return userFiltered.filter((l: any) => isCallDueToday(l, today));
        }
        return userFiltered.filter((l: any) =>
            leadMatchesDueDatePeriod(l, crmSalesPeriod, CRM_QUARTER_MONTH_BLOCKS)
        );
    }, [userFiltered, todayOnly, crmSalesPeriod]);

    const activeCalls = useMemo(
        () => periodFiltered.filter((l: any) => !isActivityCompleted(l)),
        [periodFiltered]
    );
    const completedCalls = useMemo(
        () => periodFiltered.filter((l: any) => isActivityCompleted(l)),
        [periodFiltered]
    );
    const visibleCalls = listTab === 'active' ? activeCalls : completedCalls;
    const totalCallsCount = periodFiltered.length;
    const highPotentialClientCount = useMemo(() => {
        const accountKeys = new Set<string>();
        periodFiltered.forEach((l: any) => {
            const interest = String(l?.interestStatus || '').trim().toLowerCase();
            if (interest !== 'interested' && interest !== 'waiting') return;
            const aid = String(l?.accountId || '').trim();
            const aname = String(l?.company || '').trim().toLowerCase();
            if (aid) accountKeys.add(`id:${aid}`);
            else if (aname) accountKeys.add(`name:${aname}`);
        });
        return accountKeys.size;
    }, [periodFiltered]);
    const notInterestedCallsCount = useMemo(
        () =>
            periodFiltered.filter(
                (l: any) => String(l?.interestStatus || '').trim().toLowerCase() === 'not_interested'
            ).length,
        [periodFiltered]
    );
    const deadlineCallsCount = useMemo(
        () =>
            periodFiltered.filter(
                (l: any) => String(l?.autoGeneratedType || '').trim() === 'request_deadline'
            ).length,
        [periodFiltered]
    );

    const handleToggleToday = () => {
        if (todayOnly) {
            setTodayOnly(false);
            setFollowUpHint(null);
        } else {
            setTodayOnly(true);
        }
    };

    const deadlineTagColor = (tag: string): string | null => {
        const t = String(tag || '').trim().toLowerCase();
        if (t === 'offer acceptance deadline') return '#facc15'; // yellow
        if (t === 'deposit deadline') return '#3b82f6'; // blue
        if (t === 'full payment deadline') return '#22c55e'; // green
        if (t === 'urgent') return '#ef4444'; // red
        return null;
    };

    const isUrgentDeadlineCall = (lead: any): boolean => {
        if (String(lead?.autoGeneratedType || '') !== 'request_deadline') return false;
        const due = String(lead?.dueDate || lead?.date || '').slice(0, 10);
        return !!due && due === toLocalYmd();
    };

    return (
        <div className="flex-1 min-h-0 flex flex-col gap-3">
            <div className="flex flex-wrap items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                    <button
                        type="button"
                        onClick={() => setListTab('active')}
                        className="px-3 py-1.5 rounded-lg text-xs font-bold border transition-all"
                        style={{
                            backgroundColor: listTab === 'active' ? `${colors.primary}20` : colors.bg,
                            borderColor: listTab === 'active' ? colors.primary : colors.border,
                            color: listTab === 'active' ? colors.primary : colors.textMuted,
                        }}
                    >
                        Active ({activeCalls.length})
                    </button>
                    <button
                        type="button"
                        onClick={() => setListTab('completed')}
                        className="px-3 py-1.5 rounded-lg text-xs font-bold border transition-all"
                        style={{
                            backgroundColor: listTab === 'completed' ? `${colors.green}20` : colors.bg,
                            borderColor: listTab === 'completed' ? colors.green : colors.border,
                            color: listTab === 'completed' ? colors.green : colors.textMuted,
                        }}
                    >
                        Completed ({completedCalls.length})
                    </button>
                    <button
                        type="button"
                        onClick={() => setListTab('report')}
                        className="px-3 py-1.5 rounded-lg text-xs font-bold border transition-all"
                        style={{
                            backgroundColor: listTab === 'report' ? `${colors.cyan}20` : colors.bg,
                            borderColor: listTab === 'report' ? colors.cyan : colors.border,
                            color: listTab === 'report' ? colors.cyan : colors.textMuted,
                        }}
                    >
                        Report
                    </button>
                    {listTab !== 'report' ? (
                        <button
                            type="button"
                            onClick={handleToggleToday}
                            className="px-3 py-1.5 rounded-lg text-xs font-bold border transition-all"
                            style={{
                                backgroundColor: todayOnly ? `${colors.orange}20` : colors.bg,
                                borderColor: todayOnly ? colors.orange : colors.border,
                                color: todayOnly ? colors.orange : colors.textMuted,
                            }}
                        >
                            {todayOnly ? 'Today' : 'All in period'}
                        </button>
                    ) : null}
                </div>
                {!readOnly && onAddSalesCall ? (
                    <button
                        type="button"
                        onClick={onAddSalesCall}
                        className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-bold border"
                        style={{ backgroundColor: colors.primary, borderColor: colors.primary, color: '#000' }}
                    >
                        <Plus size={14} /> Add Sales Call
                    </button>
                ) : null}
            </div>

            {followUpHint ? (
                <p className="text-xs px-3 py-2 rounded-lg border" style={{ borderColor: colors.orange, color: colors.orange }}>
                    {followUpHint}
                </p>
            ) : null}

            {listTab === 'report' ? (
                <CrmCallReportView
                    theme={theme}
                    salesCalls={salesCalls}
                    crmSalesPeriod={crmSalesPeriod}
                    createdByUserFilterId={createdByUserFilterId}
                    crmFilterUsers={crmFilterUsers}
                    activePropertyId={activePropertyId}
                />
            ) : null}

            {listTab !== 'report' ? (
            <>
            <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-2">
                <div className="rounded-lg border px-3 py-2" style={{ borderColor: colors.border, backgroundColor: colors.card }}>
                    <div className="text-[10px] uppercase font-bold tracking-wide" style={{ color: colors.textMuted }}>
                        Total Calls
                    </div>
                    <div className="text-lg font-black" style={{ color: colors.textMain }}>
                        {totalCallsCount}
                    </div>
                </div>
                <div className="rounded-lg border px-3 py-2" style={{ borderColor: colors.border, backgroundColor: colors.card }}>
                    <div className="text-[10px] uppercase font-bold tracking-wide" style={{ color: colors.textMuted }}>
                        High Potential Client
                    </div>
                    <div className="text-lg font-black" style={{ color: colors.primary }}>
                        {highPotentialClientCount}
                    </div>
                </div>
                <div className="rounded-lg border px-3 py-2" style={{ borderColor: colors.border, backgroundColor: colors.card }}>
                    <div className="text-[10px] uppercase font-bold tracking-wide" style={{ color: colors.textMuted }}>
                        Not Interested Calls
                    </div>
                    <div className="text-lg font-black" style={{ color: colors.red || '#ef4444' }}>
                        {notInterestedCallsCount}
                    </div>
                </div>
                <div className="rounded-lg border px-3 py-2" style={{ borderColor: colors.border, backgroundColor: colors.card }}>
                    <div className="text-[10px] uppercase font-bold tracking-wide" style={{ color: colors.textMuted }}>
                        Deadlines Count
                    </div>
                    <div className="text-lg font-black" style={{ color: colors.orange }}>
                        {deadlineCallsCount}
                    </div>
                </div>
            </div>

            <div className="flex-1 min-h-0 overflow-y-auto rounded-xl border" style={{ borderColor: colors.border, backgroundColor: colors.card }}>
                {visibleCalls.length === 0 ? (
                    <div className="p-8 text-center text-sm" style={{ color: colors.textMuted }}>
                        No {listTab === 'active' ? 'active' : 'completed'} sales calls for this filter.
                    </div>
                ) : (
                    <table className="w-full text-sm">
                        <thead>
                            <tr className="border-b text-[10px] uppercase tracking-wider" style={{ borderColor: colors.border, color: colors.textMuted }}>
                                <th className="text-left p-3">Due</th>
                                <th className="text-left p-3">Urgent</th>
                                <th className="text-left p-3">Account</th>
                                <th className="text-left p-3">Subject</th>
                                <th className="text-left p-3">Tags</th>
                                <th className="text-left p-3">Contact person</th>
                                <th className="text-left p-3">Email</th>
                                <th className="text-left p-3">Phone Number</th>
                                <th className="text-left p-3">Assign to</th>
                                <th className="text-right p-3">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {visibleCalls.map((lead: any) => (
                                <tr key={lead.id} className="border-b hover:bg-white/5" style={{ borderColor: colors.border }}>
                                    <td className="p-3 whitespace-nowrap" style={{ color: colors.textMain }}>
                                        {formatCallDueDate(lead)}
                                    </td>
                                    <td className="p-3 whitespace-nowrap">
                                        {isUrgentDeadlineCall(lead) ? (
                                            <span
                                                className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold"
                                                style={{ backgroundColor: 'rgba(239,68,68,0.16)', color: '#ef4444' }}
                                            >
                                                <span className="inline-block w-1.5 h-1.5 rounded-full" style={{ backgroundColor: '#ef4444' }} />
                                                Urgent
                                            </span>
                                        ) : (
                                            <span style={{ color: colors.textMuted }}>—</span>
                                        )}
                                    </td>
                                    <td className="p-3">
                                        <button type="button" className="font-semibold hover:underline text-left" style={{ color: colors.primary }} onClick={() => onOpenLeadProfile(lead)}>
                                            {lead.company || '—'}
                                        </button>
                                    </td>
                                    <td className="p-3" style={{ color: colors.textMain }}>{lead.subject || '—'}</td>
                                    <td className="p-3">
                                        <div className="flex flex-wrap gap-1">
                                            {(Array.isArray(lead.tags) ? lead.tags : []).map((tag: string, idx: number) => {
                                                const tagKey = String(tag || '').trim().toLowerCase();
                                                const isDeadlineAnchorTag =
                                                    tagKey === 'request deadline' &&
                                                    String(lead?.autoGeneratedType || '') === 'request_deadline';
                                                const renderedTag =
                                                    isDeadlineAnchorTag
                                                        ? String(lead?.subject || lead?.requestName || 'Request').trim() || 'Request'
                                                        : tag;
                                                const tc = deadlineTagColor(tag) || getTagColor(tag, colors.primary);
                                                return (
                                                    <span
                                                        key={`${tag}-${idx}`}
                                                        className="px-1.5 py-0.5 rounded text-[10px] font-semibold"
                                                        style={{ backgroundColor: `${tc}22`, color: tc }}
                                                    >
                                                        {renderedTag}
                                                    </span>
                                                );
                                            })}
                                            {!Array.isArray(lead.tags) || !lead.tags.length ? (
                                                <span style={{ color: colors.textMuted }}>—</span>
                                            ) : null}
                                        </div>
                                    </td>
                                    <td className="p-3" style={{ color: colors.textMuted }}>{lead.contact || '—'}</td>
                                    <td className="p-3" style={{ color: colors.textMuted }}>{lead.email || '—'}</td>
                                    <td className="p-3" style={{ color: colors.textMuted }}>{lead.phone || '—'}</td>
                                    <td className="p-3 whitespace-nowrap" style={{ color: colors.textMain }}>
                                        {resolveCrmCallCreatorName(lead, crmFilterUsers)}
                                    </td>
                                    <td className="p-3">
                                        <div className="flex justify-end gap-1">
                                            {accountHasCallHistory(lead, { new: salesCalls }) ? (
                                                <button type="button" title="Details" className="p-2 rounded-lg border" style={{ borderColor: colors.border, color: colors.textMuted }} onClick={() => setDetailsLead(lead)}>
                                                    <ScrollText size={14} />
                                                </button>
                                            ) : null}
                                            {!readOnly && listTab === 'active' ? (
                                                <>
                                                    <button type="button" title="Log call" className="p-2 rounded-lg border" style={{ borderColor: colors.border, color: colors.primary }} onClick={() => setLogCallLead(lead)}>
                                                        <PhoneCall size={14} />
                                                    </button>
                                                    <button
                                                        type="button"
                                                        title="Mark completed"
                                                        className="px-2 py-1 rounded-lg text-[10px] font-bold border"
                                                        style={{ borderColor: colors.green, color: colors.green }}
                                                        onClick={() => onToggleActivityCompleted(lead, true)}
                                                    >
                                                        Done
                                                    </button>
                                                </>
                                            ) : null}
                                            {!readOnly && listTab === 'completed' ? (
                                                <button
                                                    type="button"
                                                    title="Mark as active"
                                                    className="px-2 py-1 rounded-lg text-[10px] font-bold border"
                                                    style={{ borderColor: colors.orange, color: colors.orange }}
                                                    onClick={() => onToggleActivityCompleted(lead, false)}
                                                >
                                                    Undo
                                                </button>
                                            ) : null}
                                            {canEditSalesCalls && onEditCall ? (
                                                <button
                                                    type="button"
                                                    title="Edit call"
                                                    className="p-2 rounded-lg border"
                                                    style={{ borderColor: colors.border, color: colors.textMain }}
                                                    onClick={() => onEditCall(lead)}
                                                >
                                                    <Edit size={14} />
                                                </button>
                                            ) : null}
                                            {canDeleteSalesCalls && onDeleteCall ? (
                                                <button
                                                    type="button"
                                                    title="Delete call"
                                                    className="p-2 rounded-lg border"
                                                    style={{ borderColor: colors.red || '#ef4444', color: colors.red || '#ef4444' }}
                                                    onClick={() => onDeleteCall(lead)}
                                                >
                                                    <Trash2 size={14} />
                                                </button>
                                            ) : null}
                                        </div>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                )}
            </div>
            </>
            ) : null}

            <LogCallModal
                open={!!logCallLead}
                onClose={() => setLogCallLead(null)}
                onSave={(data) => {
                    if (logCallLead) onLogCallSave(logCallLead, data);
                    setLogCallLead(null);
                }}
                lead={logCallLead}
                theme={theme}
                readOnly={readOnly}
            />

            <CallDetailsModal
                open={!!detailsLead}
                onClose={() => setDetailsLead(null)}
                lead={detailsLead}
                salesCalls={salesCalls}
                crmLeads={{ new: salesCalls }}
                theme={theme}
            />
        </div>
    );
}
